### ISSUE TITLE
Add support for mobile app

### ISSUE THREAD

**Issue by rsre** [korodit/sn-themes#2]
Currently if you try to activate the theme on mobile the app says it's not available.

What changes would be needed to support the mobile app? Would just adding the mobile CSS classes work?

**Comment by orestarod** [comment]
Solarized Dark indeed does not work, but Gruvbox Dark theme works for me on mobile, so I will have to check what the differences are to transfer to Solarized. It might take a while though because I am full with university until end of June, so I am open to a PR in case you want to hasten the process.

**Comment by rsre** [comment]
The most evident changes I see are the extra CSS classes. I'll try adding those when I get some free time. But before that I'll have to manage to serve the theme from my server to test it.

I'll keep you updated.
